import { ContentItem } from "./types";

// Demo jokes for when Supabase isn't connected yet
export const DEMO_JOKES: ContentItem[] = [
  {
    id: "demo-1",
    type: "dad_joke",
    category: "dad_jokes",
    title: "Why don't scientists trust atoms?",
    body: "Because they make up everything!",
    image_url: null,
    source: "demo",
    source_id: "demo-1",
    score: 8.5,
    like_count: 42,
    dislike_count: 3,
    share_count: 15,
    view_count: 200,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    type: "dark_joke",
    category: "dark_humor",
    title: null,
    body: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    image_url: null,
    source: "demo",
    source_id: "demo-2",
    score: 9.0,
    like_count: 67,
    dislike_count: 5,
    share_count: 30,
    view_count: 350,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    type: "text_joke",
    category: "programming",
    title: "A SQL query walks into a bar, walks up to two tables and asks...",
    body: '"Can I join you?"',
    image_url: null,
    source: "demo",
    source_id: "demo-3",
    score: 7.5,
    like_count: 38,
    dislike_count: 8,
    share_count: 12,
    view_count: 180,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    type: "one_liner",
    category: "pun",
    title: null,
    body: "I'm reading a book about anti-gravity. It's impossible to put down!",
    image_url: null,
    source: "demo",
    source_id: "demo-4",
    score: 7.0,
    like_count: 29,
    dislike_count: 6,
    share_count: 8,
    view_count: 150,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    type: "dad_joke",
    category: "dad_jokes",
    title: "What do you call a fake noodle?",
    body: "An impasta!",
    image_url: null,
    source: "demo",
    source_id: "demo-5",
    score: 8.0,
    like_count: 55,
    dislike_count: 4,
    share_count: 22,
    view_count: 280,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-6",
    type: "text_joke",
    category: "general",
    title: "Why did the scarecrow win an award?",
    body: "Because he was outstanding in his field!",
    image_url: null,
    source: "demo",
    source_id: "demo-6",
    score: 7.8,
    like_count: 45,
    dislike_count: 7,
    share_count: 18,
    view_count: 220,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-7",
    type: "dark_joke",
    category: "dark_humor",
    title: null,
    body: "My grandfather has the heart of a lion... and a lifetime ban from the zoo.",
    image_url: null,
    source: "demo",
    source_id: "demo-7",
    score: 8.8,
    like_count: 72,
    dislike_count: 10,
    share_count: 35,
    view_count: 400,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-8",
    type: "one_liner",
    category: "programming",
    title: null,
    body: "There are only 10 types of people in the world: those who understand binary and those who don't.",
    image_url: null,
    source: "demo",
    source_id: "demo-8",
    score: 7.2,
    like_count: 33,
    dislike_count: 9,
    share_count: 14,
    view_count: 170,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-9",
    type: "dad_joke",
    category: "dad_jokes",
    title: "I used to hate facial hair...",
    body: "But then it grew on me.",
    image_url: null,
    source: "demo",
    source_id: "demo-9",
    score: 8.2,
    like_count: 50,
    dislike_count: 3,
    share_count: 20,
    view_count: 250,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-10",
    type: "text_joke",
    category: "general",
    title: "What's the best thing about Switzerland?",
    body: "I don't know, but the flag is a big plus.",
    image_url: null,
    source: "demo",
    source_id: "demo-10",
    score: 8.4,
    like_count: 61,
    dislike_count: 2,
    share_count: 25,
    view_count: 310,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-11",
    type: "one_liner",
    category: "pun",
    title: null,
    body: "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    image_url: null,
    source: "demo",
    source_id: "demo-11",
    score: 6.5,
    like_count: 20,
    dislike_count: 5,
    share_count: 7,
    view_count: 120,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-12",
    type: "dark_joke",
    category: "dark_humor",
    title: "I have a joke about trickle-down economics.",
    body: "But 99% of you will never get it.",
    image_url: null,
    source: "demo",
    source_id: "demo-12",
    score: 9.1,
    like_count: 80,
    dislike_count: 8,
    share_count: 40,
    view_count: 450,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];
