-- DayFlow Migration 002: Align schema with app data model
--
-- The 001 migration used UUID types for IDs, but the app uses TEXT IDs:
--   • Categories: text slugs ('sys-deep-work', 'cust-social', etc.)
--   • Activities / logs / goals: UUID-formatted text generated by generateId()
--
-- This migration drops and recreates tables with TEXT ids, adds all columns
-- present in the local SQLite schema (schema.ts), and adds the goals table.
-- Safe to run on a fresh Supabase project (no user data yet).
--
-- Run in Supabase Dashboard → SQL Editor, or via: supabase db push

-- ─── Drop old tables (reverse FK order) ─────────────────────────────────────
DROP TABLE IF EXISTS public.ai_usage CASCADE;
DROP TABLE IF EXISTS public.experience_logs CASCADE;
DROP TABLE IF EXISTS public.activities CASCADE;
DROP TABLE IF EXISTS public.goals CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ─── Users ───────────────────────────────────────────────────────────────────
-- Extends auth.users; id is the Supabase auth UUID stored as TEXT for
-- consistency with the app's user_id fields.
CREATE TABLE public.users (
  id           TEXT PRIMARY KEY,  -- = auth.uid()::text
  email        TEXT NOT NULL,
  settings     JSONB NOT NULL DEFAULT '{
    "day_start": "06:00",
    "quiet_hours_start": "22:00",
    "quiet_hours_end": "08:00",
    "nudge_enabled": true,
    "timezone": "UTC"
  }'::jsonb,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users_own" ON public.users
  FOR ALL USING (auth.uid()::text = id);

-- ─── Categories ──────────────────────────────────────────────────────────────
-- user_id = NULL → system category (readable by all, not writable by users).
-- user_id = <user> → custom category owned by that user.
CREATE TABLE public.categories (
  id           TEXT PRIMARY KEY,  -- e.g. 'sys-deep-work', 'cust-social'
  user_id      TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  color        TEXT NOT NULL,
  icon         TEXT NOT NULL,
  is_system    INTEGER NOT NULL DEFAULT 0,
  sort_order   INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
-- System categories (user_id IS NULL) are readable by everyone
CREATE POLICY "categories_read" ON public.categories
  FOR SELECT USING (user_id IS NULL OR auth.uid()::text = user_id);
CREATE POLICY "categories_write" ON public.categories
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);
CREATE POLICY "categories_update" ON public.categories
  FOR UPDATE USING (auth.uid()::text = user_id);
CREATE POLICY "categories_delete" ON public.categories
  FOR DELETE USING (auth.uid()::text = user_id);

-- Seed system categories matching app's systemCategories.ts IDs
INSERT INTO public.categories (id, user_id, name, color, icon, is_system, sort_order) VALUES
  ('sys-deep-work',  NULL, 'Deep Work', '#6366F1', '🧠', 1, 0),
  ('sys-meetings',   NULL, 'Meetings',  '#F59E0B', '👥', 1, 1),
  ('sys-admin',      NULL, 'Admin',     '#64748B', '📋', 1, 2),
  ('sys-health',     NULL, 'Health',    '#10B981', '💪', 1, 3),
  ('sys-learning',   NULL, 'Learning',  '#3B82F6', '📚', 1, 4),
  ('sys-personal',   NULL, 'Personal',  '#EC4899', '✨', 1, 5),
  ('sys-creative',   NULL, 'Creative',  '#F97316', '🎨', 1, 6),
  ('sys-rest',       NULL, 'Rest',      '#8B5CF6', '😴', 1, 7);

-- ─── Activities ──────────────────────────────────────────────────────────────
-- Mirrors the local SQLite schema in schema.ts exactly.
-- `deleted = 1` means soft-deleted (hidden from queries but kept for sync).
-- `synced` is intentionally absent — it's a local-only tracking field.
CREATE TABLE public.activities (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  activity_type       TEXT NOT NULL DEFAULT 'TIME_BLOCK',
  title               TEXT NOT NULL,
  description         TEXT,
  assigned_date       TEXT,
  start_time          TEXT NOT NULL,
  duration_minutes    INTEGER NOT NULL DEFAULT 0,
  category_id         TEXT REFERENCES public.categories(id),
  is_scheduled        INTEGER NOT NULL DEFAULT 1,
  mindset_prompt      TEXT,
  mindset_overridden  INTEGER NOT NULL DEFAULT 0,
  recurrence_type     TEXT NOT NULL DEFAULT 'NONE',
  recurrence_days     TEXT,
  subtasks            TEXT,  -- JSON array of { id, title, done }
  status              TEXT NOT NULL DEFAULT 'PLANNED',
  priority            TEXT NOT NULL DEFAULT 'MEDIUM',
  actual_start        TEXT,
  actual_end          TEXT,
  goal_id             TEXT,  -- FK added after goals table is created
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL,
  deleted             INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_activities_user_start ON public.activities (user_id, start_time);
CREATE INDEX idx_activities_user_date  ON public.activities (user_id, assigned_date);

ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "activities_own" ON public.activities
  FOR ALL USING (auth.uid()::text = user_id);

-- ─── Experience Logs ─────────────────────────────────────────────────────────
CREATE TABLE public.experience_logs (
  id              TEXT PRIMARY KEY,
  activity_id     TEXT NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
  user_id         TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  mood            INTEGER NOT NULL,
  energy          INTEGER NOT NULL,
  completion_pct  INTEGER NOT NULL DEFAULT 0,
  reflection      TEXT,
  would_repeat    TEXT,
  log_phase       TEXT NOT NULL DEFAULT 'AFTER',
  logged_at       TEXT NOT NULL,
  deleted         INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_logs_activity  ON public.experience_logs (activity_id);
CREATE INDEX idx_logs_user      ON public.experience_logs (user_id, logged_at);

ALTER TABLE public.experience_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "logs_own" ON public.experience_logs
  FOR ALL USING (auth.uid()::text = user_id);

-- ─── Goals ───────────────────────────────────────────────────────────────────
CREATE TABLE public.goals (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  metric_type   TEXT NOT NULL DEFAULT 'TIME',
  target_value  INTEGER NOT NULL,
  frequency     TEXT NOT NULL DEFAULT 'DAILY',
  category_id   TEXT REFERENCES public.categories(id),
  specific_days TEXT,
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE INDEX idx_goals_user ON public.goals (user_id, is_active);

ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "goals_own" ON public.goals
  FOR ALL USING (auth.uid()::text = user_id);

-- ─── Add FK from activities → goals (now that goals table exists) ─────────────
ALTER TABLE public.activities
  ADD CONSTRAINT fk_activities_goal
  FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE SET NULL;

-- ─── updated_at auto-trigger ─────────────────────────────────────────────────
-- Note: activities and goals store updated_at as TEXT (ISO string set by the app).
-- This trigger keeps the users table updated_at in sync on the Postgres side.
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
